name: Build and Release

on: workflow_dispatch
  
jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/ava

    steps:        
    - uses: actions/checkout@v2

    - name: Get version number
      uses: naminodarie/get-net-sdk-project-versions-action@v1.1.1
      id: get-version
      with:
        proj-path: src/ava/ava.csproj

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Publish - Windows
      run: dotnet publish -r win-x64 -p:PublishSingleFile=true --self-contained true -c Release
    - name: Publish - Linux
      run: dotnet publish -r linux-x64 -p:PublishSingleFile=true --self-contained true -c Release

    - name: Prepare Releases
      run: |
        tar cz ava_win_${{steps.get-version.outputs.version}}.tar.gz bin/Release/net5.0/win-x64/publish
        tar cz ava_linux_${{steps.get-version.outputs.version}}.tar.gz bin/Release/net5.0/linux-x64/publish

    - name: List
      run: ls -alt

