name: .NET

on: workflow_dispatch
  
jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/lva

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Publish - Windows
      run: dotnet publish -r win-x64 -p:PublishSingleFile=true --self-contained true -c Release
    - name: Publish - Linux
      run: dotnet publish -r linux-x64 -p:PublishSingleFile=true --self-contained true -c Release
