name: Sandbox

on: workflow_dispatch
  
jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/ava

    steps:        
    - uses: actions/checkout@v2
    - name: List
      run: |
        ls -alt
        cat ava.csproj
        cat ./ava.csproj
        cat ./src/ava/ava.csproj

    - name: Get version number
      uses: naminodarie/get-net-sdk-project-versions-action@v1.1.1
      id: get-version
      with:
        proj-path: ./src/ava/ava.csproj
    - name: Show versions
      run: |
        echo "${{steps.get-version.outputs.version}}"
        echo "${{steps.get-version.outputs.version-prefix}}" 
        echo "${{steps.get-version.outputs.version-suffix}}" 
        echo "${{steps.get-version.outputs.package-version}}" 
        echo "${{steps.get-version.outputs.assembly-version}}" 
        echo "${{steps.get-version.outputs.file-version}}" 
        echo "${{steps.get-version.outputs.informational-version}}" 
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Publish - Windows
      run: dotnet publish -r win-x64 -p:PublishSingleFile=true --self-contained true -c Release
    - name: Publish - Linux
      run: dotnet publish -r linux-x64 -p:PublishSingleFile=true --self-contained true -c Release
